project:
  type: website

website:
  # title: "Shune Kawaoto"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: About
      - href: AcademicExperience.qmd
        text: Academic Experience
      - href: WorkExperience.qmd
        text: Work Experience
        
  page-footer:  
    right: "&copy; 2024, Shune Kawaoto"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
