---
toc: false
---
# Coursework

<!-- Your regular text <span style="float: right;">right aligned text</span> -->

- STATS 20 <span style="float: right;">Introduction to Statistical Programming with R</span>
- STATS 100A <span style="float: right;">Introduction to Probability</span>
- STATS 100B <span style="float: right;">Introduction to Mathematical Statistics</span>
- STATS 100C <span style="float: right;">Linear Models</span>
- STATS 101A <span style="float: right;">Introduction to Data Analysis and Regression</span>
- STATS 101B <span style="float: right;">Introduction to Design and Analysis of Experiment</span>
- STATS 101C <span style="float: right;">Introduction to Statistical Models and Data Mining</span>
- STATS 102A <span style="float: right;">Introduction to Computational Statistics with R</span>
- STATS 102B <span style="float: right;">Introduction to Computation and Optimization for Statistics</span>
- STATS 102C <span style="float: right;">Introduction to Monte Carlo Methods</span>
- STATS C155 <span style="float: right;">Applied Sampling</span>
- STATS C173 <span style="float: right;">Applied Geostatistics</span>
- COM SCI 31 <span style="float: right;">Introduction to Computer Science I</span>
- COM SCI 32 <span style="float: right;">Introduction to Computer Science II</span>
- MATH 115A <span style="float: right;">Linear Algebra</span>
- MATH 131A <span style="float: right;">Analysis</span>
- GEOG 7 <span style="float: right;">Introduction to Geographic Information Systems</span>
